### ISSUE TITLE
nodejs crashes when trying to use rooms

### ISSUE THREAD

**Issue by siddo420** [cayasso/primus.io#8] opened 2014-03-13 16:49 UTC
I may be doing something wrong since I just started using it but it shouldn't crash the server at least 

I am using primus-redis-rooms

/Users/siddo/fun/node-web-projects/test3/node_modules/primus-rooms/lib/index.js:152
      return this._rooms[fn].apply(this._rooms, arguments);
                             ^
TypeError: Cannot call method 'apply' of undefined
    at Sparky.<anonymous> (/Users/siddo/fun/node-web-projects/test3/node_modules/primus-rooms/lib/index.js:152:30)
    at Sparky.<anonymous> (/Users/siddo/fun/node-web-projects/test3/app.js:410:13)
    at Sparky.EventEmitter.emit (events.js:117:20)
    at decoding (/Users/siddo/fun/node-web-projects/test3/node_modules/primus/spark.js:206:13)
    at Primus.decoder (/Users/siddo/fun/node-web-projects/test3/node_modules/primus/parsers/json.js:32:3)
    at Sparky.message (/Users/siddo/fun/node-web-projects/test3/node_modules/primus/spark.js:179:12)
    at Sparky.EventEmitter.emit (events.js:95:17)
    at Socket.emit (/Users/siddo/fun/node-web-projects/test3/node_modules/primus/spark.js:315:11)
    at Socket.EventEmitter.emit [as $emit] (events.js:95:17)
    at SocketNamespace.handlePacket (/Users/siddo/fun/node-web-projects/test3/node_modules/socket.io/lib/namespace.js:353:20)

server:
primus.on( 'connection', function ( spark ) {
  spark.on('data', function(data) {
    
    data = data || {};
    var action = data.action;
    var room = data.room;

    // join a room
    if ('join' === action) {
      spark.join(room, function () {

        // send message to this client
        spark.write('you joined room ' + room);

        // send message to all clients except this one
        spark.room(room).except(spark.id).write(spark.id + ' joined room ' + room);
      });
    }

    // leave a room
    if ('leave' === action) {
      spark.leave(room, function () {

        // send message to this client
        spark.write('you left room ' + room);
      });
    }

    // leave a room
    if ('message' === action) {
        // send message to this client
      //spark.write( data.msg );
      spark.room(room).except(spark.id).write( data.msg );
    }    
  });  

client:
      primus.on('open', function () {
        // Send request to join the news room
        primus.write({ action: 'join', room: 'news' });

        // Send request to leave the news room
        //primus.write({ action: 'leave', room: 'news' });

        // print server message
        primus.on( 'data', function (msg) {
          $('#message_area').append( '<p>' + msg + '</p>' );
        });        
        
        $( '#send_chat' ).click( function() { 
          primus.write({ action: 'message', msg: $('#message').val(), room: 'news' }); 
        });
        
        
      });

**Comment by cayasso** [comment] 2015-07-07 13:36
I will close this issue because I cannot reproduce this issue by using primus-rooms, please check with "primus-redis-rooms" author.

**Closed by cayasso** 2015-07-07 13:36 UTC
